### ISSUE TITLE
Getting error while building fatJar 

### ISSUE THREAD

**Issue by aryaKetan** [javaslang/javaslang#1856] opened 2017-02-08 10:14 UTC
What went wrong:

I have a docker image on which I run my build process. For my application, I use gradle as build tool and am creating a fatJar using task fatJar. I am using javaslang in my application and while creating the fatJar, I am getting the following error.  

Could not expand ZIP '/var/lib/jenkins/.gradle/caches/modules-2/files-2.1/io.javaslang/javaslang/2.0.5/86a8f8c75254d948dd128388b1097183e8c6564b/javaslang-2.0.5.jar'.
> Could not copy zip entry /var/lib/jenkins/.gradle/caches/modules-2/files-2.1/io.javaslang/javaslang/2.0.5/86a8f8c75254d948dd128388b1097183e8c6564b/javaslang-2.0.5.jar!javaslang/?$Memoized.class to '/var/lib/jenkins/workspace/fk-tns-build/applications/services/build/tmp/expandedArchives/javaslang-2.0.5.jar_5qozg2y23zzsrefcm5v8akl0q/javaslang/?$Memoized.class'

I believe this is due to the class λ. Any pointers?

**Comment by danieldietrich** [comment] 2017-02-08 10:25
@aryaKetan yes, we have a class called `λ.class`. It seems to be charset-related.

@oehme is it possible to set charset to UTF-8 when using the Gradle fatJar task?

**Comment by danieldietrich** [comment] 2017-02-08 10:40
@aryaKetan we had a similar issue (#223). The workaround was to set the file.encoding system property, either in the JAVA_OPTS or in the GRADLE_OPTS. See a complete description [here](https://github.com/johnrengelman/shadow/issues/223#issuecomment-237528182). /cc @oehme

**Comment by RobWin** [comment] 2017-02-08 11:02
Try to set sun.jnu.encoding=UTF-8

**Comment by oehme** [comment] 2017-02-08 11:17
Gradle has no "fatJar" task, so I'm not sure what you are referring to. Gradle's `Jar` task uses UTF-8 for metadata (file name) encoding, because that is what the JVM expects. Sounds like you are using some community plugin which uses the system encoding instead.

**Comment by aryaKetan** [comment] 2017-02-08 12:13
@oehme : We have written this task : 
task fatJar(type: Jar) {
    manifest {
        attributes 'Implementation-Title': project.name,
                'Implementation-Version': version,
                'Main-Class': project.mainClassName
    }
    archiveName project.name + ".jar"
    zip64=true
    baseName = project.name
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}

In this, during zipTree while copying the λMemoized.class , I am getting the above error.  

I added gradle.properties with content 
systemProp.file.encoding=UTF-8

Still, same error. 

Will try to set JAVA OPTS now.

**Comment by RobWin** [comment] 2017-02-08 12:47
Did you try `systemProp.sun.jnu.encoding=UTF-8`?

**Comment by oehme** [comment] 2017-02-08 13:14
> Did you try systemProp.sun.jnu.encoding=UTF-8?

If you have to mess with these settings, then there is a bug. This should not be an acceptable solution. Instead please let us know if you are experiencing such problems with Gradle's core APIs. I've created an issue for this.

@aryaKetan Thank you for the example. The problem is not in the Jar task, but in how Gradle expends zips using the `zipTree` method.

**Comment by danieldietrich** [comment] 2017-02-08 13:31
Stefan created the following issue: gradle/gradle#1363

**Comment by danieldietrich** [comment] 2017-02-08 13:31
@aryaKetan I will close this issue because it is not directly related to Javaslang. Thank you for reporting!

**Closed by danieldietrich** 2017-02-08 13:31 UTC
Labels: question, «non-public»
