### ISSUE TITLE
Fatjar/Onejar unable to launch because of λ class

### ISSUE THREAD

**Issue by Pyeroh** [javaslang/javaslang#1378] opened 2016-06-12 23:42 UTC
Hi, 
I'm using your (awesome) library in my project, and I need to build a onejar (a jar with every dependency flatened). I build my project with Gradle, and the Shadow plugin.

I don't know if it's Shadow related, or Gradle, or the name of this class, but when my project is built, it contains a ?.class in the package javaslang, and the jar is unable to launch, because of a `ClassNotFoundException: javaslang.?`

Any idea about this ? Does this issue need more precisions ?

BTW, I don't think it's a good idea to name a class with such a custom character, but I may be wrong...

**Comment by danieldietrich** [comment] 2016-06-13 05:24
There has been an [issue with AWS Lambda](https://forums.aws.amazon.com/thread.jspa?threadID=229364) in the past, which sounds similar.

Unicode characters are part of the Java Spec. Maybe you need to set the encoding somewhere? Are you a windows user?

**Comment by danieldietrich** [comment] 2016-06-13 19:21
Hi @Pyeroh,

I've created a maven-shade-plugin test project: [javaslang-shade-test](https://github.com/danieldietrich/javaslang-shade-test)

Please check it out and follow the two build steps.

It works fine on my Mac. I need some feedback to further investigate this issue.

Please add some info on the build environment you use.

Thanks in advance,

Daniel

**Comment by Pyeroh** [comment] 2016-06-13 21:53
Hi,
A bunch of informations about my environnement :
- Gradle (with the wrapper, 2.13)
- Java 1.8.0_92
- Windows 7
- Eclipse

All dependencies are loaded via Gradle, but apparently, in my local Gradle repo, Javaslang contains correctly encoded class files...
I'm not very familiar with Gradle, nor with Maven, but it seems there's no way to run a maven goal from gradle.

I also tried to add compileJava.options.encoding = 'UTF-8' to my build.gradle, but it doesn't work either.

**Comment by danieldietrich** [comment] 2016-06-13 22:43
Thank you! Very interesting.

I've created the same test for Gradle: [javaslang-shadow-test](https://github.com/danieldietrich/javaslang-shadow-test).

And now the same error occurs on my machine.

I think it is a shadow plugin error - I created an issue: johnrengelman/shadow#223

I will close this issue because it is not a bug related to Javaslang.

**Closed by danieldietrich** 2016-06-13 22:43 UTC
Labels: question

**Comment by Pyeroh** [comment] 2016-06-13 22:54
Thanks a lot :D
I tried to build my project with the plugin 'application' and obviously, it works (but I prefer 'uber-jars'...)
I'll work with 'application' gradle plugin until Shadow is fixed. thanks again.

**Comment by danieldietrich** [comment] 2016-06-13 22:55
Good to hear.
Happy hacking!

**Comment by danieldietrich** [comment] 2016-08-04 12:11
suggested solution/workaround: https://github.com/johnrengelman/shadow/issues/223#issuecomment-237528182

**Comment by acmcelwee** [comment] 2016-12-08 04:46
Sorry to resurrect an old issue, but I was wondering if you have any thoughts on working around the AWS lambda runtime issue. I commented on [that forum post](https://forums.aws.amazon.com/thread.jspa?threadID=229364), but I haven't had any luck getting any javaslang-dependent code to correctly load because the classloader fails to find the `λ` class. I see you contemplated changing the class name from `λ` to `Function` in #83. Anyway, figured it can't hurt to ask if you have any suggestions. Thanks!

**Comment by danieldietrich** [comment] 2016-12-08 22:15
@acmcelwee created a minimal failing test: https://github.com/acmcelwee/javaslang-shade-test/tree/aws-lambda

Output of AWS Lambda:

```javascript
{
  "errorMessage": "java.lang.NoClassDefFoundError: javaslang/λ",
  "errorType": "java.lang.BootstrapMethodError",
  "stackTrace": [
    "javaslang.ShadeTest.myHandler(ShadeTest.java:8)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)"
  ],
  "cause": {
    "errorMessage": "javaslang/λ",
    "errorType": "java.lang.NoClassDefFoundError",
    "stackTrace": [
      "java.lang.ClassLoader.defineClass1(Native Method)",
      "java.lang.ClassLoader.defineClass(ClassLoader.java:763)",
      "java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)",
      "java.net.URLClassLoader.defineClass(URLClassLoader.java:467)",
      "java.net.URLClassLoader.access$100(URLClassLoader.java:73)",
      "java.net.URLClassLoader$1.run(URLClassLoader.java:368)",
      "java.net.URLClassLoader$1.run(URLClassLoader.java:362)",
      "java.security.AccessController.doPrivileged(Native Method)",
      "java.net.URLClassLoader.findClass(URLClassLoader.java:361)",
      "java.lang.ClassLoader.loadClass(ClassLoader.java:424)",
      "java.lang.ClassLoader.loadClass(ClassLoader.java:357)",
      "javaslang.ShadeTest.myHandler(ShadeTest.java:8)",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:498)"
    ],
    "cause": {
      "errorMessage": "javaslang.λ",
      "errorType": "java.lang.ClassNotFoundException",
      "stackTrace": [
        "java.net.URLClassLoader.findClass(URLClassLoader.java:381)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:424)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:357)",
        "java.lang.ClassLoader.defineClass1(Native Method)",
        "java.lang.ClassLoader.defineClass(ClassLoader.java:763)",
        "java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)",
        "java.net.URLClassLoader.defineClass(URLClassLoader.java:467)",
        "java.net.URLClassLoader.access$100(URLClassLoader.java:73)",
        "java.net.URLClassLoader$1.run(URLClassLoader.java:368)",
        "java.net.URLClassLoader$1.run(URLClassLoader.java:362)",
        "java.security.AccessController.doPrivileged(Native Method)",
        "java.net.URLClassLoader.findClass(URLClassLoader.java:361)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:424)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:357)",
        "javaslang.ShadeTest.myHandler(ShadeTest.java:8)",
        "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
        "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "java.lang.reflect.Method.invoke(Method.java:498)"
      ]
    }
  }
}
```

**Comment by acmcelwee** [comment] 2016-12-08 22:45
Just to demonstrate that maven shade is not the problem here, 

```sh
$ jar -tf target/shade-test-0.0.1-SNAPSHOT.jar
META-INF/MANIFEST.MF
META-INF/
javaslang/
javaslang/ShadeTest.class
META-INF/maven/
META-INF/maven/javaslang/
META-INF/maven/javaslang/shade-test/
META-INF/maven/javaslang/shade-test/pom.xml
META-INF/maven/javaslang/shade-test/pom.properties
javaslang/$.class
javaslang/API$1.class
javaslang/API$2.class
javaslang/API$For1.class
javaslang/API$For2.class
javaslang/API$For3.class
javaslang/API$For4.class
javaslang/API$For5.class
javaslang/API$For6.class
javaslang/API$For7.class
javaslang/API$For8.class
javaslang/API$Match$Case.class
javaslang/API$Match$Case0.class
javaslang/API$Match$Case1.class
javaslang/API$Match$Case2.class
javaslang/API$Match$Case3.class
javaslang/API$Match$Case4.class
javaslang/API$Match$Case5.class
javaslang/API$Match$Case6.class
javaslang/API$Match$Case7.class
javaslang/API$Match$Case8.class
javaslang/API$Match$Pattern.class
javaslang/API$Match$Pattern0$1.class
javaslang/API$Match$Pattern0$2.class
javaslang/API$Match$Pattern0.class
javaslang/API$Match$Pattern1$1.class
javaslang/API$Match$Pattern1.class
javaslang/API$Match$Pattern2$1.class
javaslang/API$Match$Pattern2.class
javaslang/API$Match$Pattern3$1.class
javaslang/API$Match$Pattern3.class
javaslang/API$Match$Pattern4$1.class
javaslang/API$Match$Pattern4.class
javaslang/API$Match$Pattern5$1.class
javaslang/API$Match$Pattern5.class
javaslang/API$Match$Pattern6$1.class
javaslang/API$Match$Pattern6.class
javaslang/API$Match$Pattern7$1.class
javaslang/API$Match$Pattern7.class
javaslang/API$Match$Pattern8$1.class
javaslang/API$Match$Pattern8.class
javaslang/API$Match.class
javaslang/API.class
javaslang/CheckedFunction0.class
javaslang/CheckedFunction1.class
javaslang/CheckedFunction2.class
javaslang/CheckedFunction3.class
javaslang/CheckedFunction4.class
javaslang/CheckedFunction5.class
javaslang/CheckedFunction6.class
javaslang/CheckedFunction7.class
javaslang/CheckedFunction8.class
javaslang/collection/
javaslang/collection/AbstractIterator.class
javaslang/collection/AbstractMap.class
javaslang/collection/Array$1.class
javaslang/collection/Array.class
javaslang/collection/ArrayModule$Combinations.class
javaslang/collection/ArrayModule.class
javaslang/collection/CharSeq$1.class
javaslang/collection/CharSeq$CharFunction.class
javaslang/collection/CharSeq$CharUnaryOperator.class
javaslang/collection/CharSeq.class
javaslang/collection/CharSeqModule$Combinations.class
javaslang/collection/CharSeqModule.class
javaslang/collection/Collections$1.class
javaslang/collection/Collections.class
javaslang/collection/Comparators$SerializableComparator.class
javaslang/collection/Comparators.class
javaslang/collection/Foldable.class
javaslang/collection/HashArrayMappedTrie.class
javaslang/collection/HashArrayMappedTrieModule$AbstractNode.class
javaslang/collection/HashArrayMappedTrieModule$Action.class
javaslang/collection/HashArrayMappedTrieModule$ArrayNode.class
javaslang/collection/HashArrayMappedTrieModule$EmptyNode.class
javaslang/collection/HashArrayMappedTrieModule$IndexedNode.class
javaslang/collection/HashArrayMappedTrieModule$LeafList$1.class
javaslang/collection/HashArrayMappedTrieModule$LeafList.class
javaslang/collection/HashArrayMappedTrieModule$LeafNode.class
javaslang/collection/HashArrayMappedTrieModule$LeafSingleton.class
javaslang/collection/HashArrayMappedTrieModule.class
javaslang/collection/HashMap.class
javaslang/collection/HashSet$1.class
javaslang/collection/HashSet$SerializationProxy.class
javaslang/collection/HashSet.class
javaslang/collection/IndexedSeq$1.class
javaslang/collection/IndexedSeq.class
javaslang/collection/IndexedSeqModule$LastIndexOfSlice.class
javaslang/collection/IndexedSeqModule$Search.class
javaslang/collection/IndexedSeqModule.class
javaslang/collection/Iterator$1.class
javaslang/collection/Iterator$10.class
javaslang/collection/Iterator$11.class
javaslang/collection/Iterator$12.class
javaslang/collection/Iterator$13.class
javaslang/collection/Iterator$14.class
javaslang/collection/Iterator$15.class
javaslang/collection/Iterator$16.class
javaslang/collection/Iterator$17.class
javaslang/collection/Iterator$18.class
javaslang/collection/Iterator$19.class
javaslang/collection/Iterator$2.class
javaslang/collection/Iterator$20.class
javaslang/collection/Iterator$21.class
javaslang/collection/Iterator$22.class
javaslang/collection/Iterator$23.class
javaslang/collection/Iterator$24.class
javaslang/collection/Iterator$25.class
javaslang/collection/Iterator$26.class
javaslang/collection/Iterator$27.class
javaslang/collection/Iterator$28.class
javaslang/collection/Iterator$29.class
javaslang/collection/Iterator$3.class
javaslang/collection/Iterator$30.class
javaslang/collection/Iterator$31.class
javaslang/collection/Iterator$32.class
javaslang/collection/Iterator$33.class
javaslang/collection/Iterator$34.class
javaslang/collection/Iterator$35.class
javaslang/collection/Iterator$36.class
javaslang/collection/Iterator$37.class
javaslang/collection/Iterator$38.class
javaslang/collection/Iterator$39.class
javaslang/collection/Iterator$4.class
javaslang/collection/Iterator$40.class
javaslang/collection/Iterator$41.class
javaslang/collection/Iterator$5.class
javaslang/collection/Iterator$6.class
javaslang/collection/Iterator$7.class
javaslang/collection/Iterator$8.class
javaslang/collection/Iterator$9.class
javaslang/collection/Iterator.class
javaslang/collection/IteratorModule$ConcatIterator.class
javaslang/collection/IteratorModule$DistinctIterator.class
javaslang/collection/IteratorModule.class
javaslang/collection/LinearSeq.class
javaslang/collection/LinearSeqModule$LastIndexOfSlice.class
javaslang/collection/LinearSeqModule$Search.class
javaslang/collection/LinearSeqModule.class
javaslang/collection/LinkedHashMap.class
javaslang/collection/LinkedHashSet$1.class
javaslang/collection/LinkedHashSet$SerializationProxy.class
javaslang/collection/LinkedHashSet.class
javaslang/collection/List$1.class
javaslang/collection/List$Cons$SerializationProxy.class
javaslang/collection/List$Cons.class
javaslang/collection/List$Nil.class
javaslang/collection/List.class
javaslang/collection/ListModule$Combinations.class
javaslang/collection/ListModule$SplitAt.class
javaslang/collection/ListModule.class
javaslang/collection/Map.class
javaslang/collection/Queue.class
javaslang/collection/RedBlackTree$1.class
javaslang/collection/RedBlackTree$Color.class
javaslang/collection/RedBlackTree.class
javaslang/collection/RedBlackTreeModule$Empty.class
javaslang/collection/RedBlackTreeModule$Node.class
javaslang/collection/RedBlackTreeModule.class
javaslang/collection/Seq$1Util.class
javaslang/collection/Seq.class
javaslang/collection/Set.class
javaslang/collection/SortedMap.class
javaslang/collection/SortedSet.class
javaslang/collection/Stack.class
javaslang/collection/Stream$1.class
javaslang/collection/Stream$2.class
javaslang/collection/Stream$3.class
javaslang/collection/Stream$4.class
javaslang/collection/Stream$Cons.class
javaslang/collection/Stream$Empty.class
javaslang/collection/Stream.class
javaslang/collection/StreamModule$AppendElements.class
javaslang/collection/StreamModule$AppendSelf.class
javaslang/collection/StreamModule$Combinations.class
javaslang/collection/StreamModule$ConsImpl.class
javaslang/collection/StreamModule$DropRight.class
javaslang/collection/StreamModule$SerializationProxy.class
javaslang/collection/StreamModule$StreamFactory.class
javaslang/collection/StreamModule$StreamIterator.class
javaslang/collection/StreamModule.class
javaslang/collection/Traversable$1.class
javaslang/collection/Traversable.class
javaslang/collection/Tree$1.class
javaslang/collection/Tree$Empty.class
javaslang/collection/Tree$Node$SerializationProxy.class
javaslang/collection/Tree$Node.class
javaslang/collection/Tree$Order.class
javaslang/collection/Tree.class
javaslang/collection/TreeMap$EntryComparator.class
javaslang/collection/TreeMap.class
javaslang/collection/TreeModule$FlatMap.class
javaslang/collection/TreeModule$Map.class
javaslang/collection/TreeModule$Replace.class
javaslang/collection/TreeModule$Traversal.class
javaslang/collection/TreeModule$Unzip.class
javaslang/collection/TreeModule$Zip.class
javaslang/collection/TreeModule$ZipAll.class
javaslang/collection/TreeModule.class
javaslang/collection/TreeSet.class
javaslang/collection/Vector$1.class
javaslang/collection/Vector.class
javaslang/collection/VectorModule$Combinations.class
javaslang/collection/VectorModule.class
javaslang/concurrent/
javaslang/concurrent/Future.class
javaslang/concurrent/FutureImpl.class
javaslang/concurrent/Promise.class
javaslang/concurrent/PromiseImpl.class
javaslang/control/
javaslang/control/Either$1.class
javaslang/control/Either$Left.class
javaslang/control/Either$LeftProjection.class
javaslang/control/Either$Right.class
javaslang/control/Either$RightProjection.class
javaslang/control/Either.class
javaslang/control/Option$1.class
javaslang/control/Option$None.class
javaslang/control/Option$Some.class
javaslang/control/Option.class
javaslang/control/Try$1.class
javaslang/control/Try$CheckedConsumer.class
javaslang/control/Try$CheckedFunction.class
javaslang/control/Try$CheckedPredicate.class
javaslang/control/Try$CheckedRunnable.class
javaslang/control/Try$CheckedSupplier.class
javaslang/control/Try$Failure.class
javaslang/control/Try$FatalException.class
javaslang/control/Try$NonFatalException.class
javaslang/control/Try$Success.class
javaslang/control/Try.class
javaslang/control/Validation$1.class
javaslang/control/Validation$Builder.class
javaslang/control/Validation$Builder3.class
javaslang/control/Validation$Builder4.class
javaslang/control/Validation$Builder5.class
javaslang/control/Validation$Builder6.class
javaslang/control/Validation$Builder7.class
javaslang/control/Validation$Builder8.class
javaslang/control/Validation$Invalid.class
javaslang/control/Validation$Valid.class
javaslang/control/Validation.class
javaslang/Function0.class
javaslang/Function1.class
javaslang/Function2.class
javaslang/Function3.class
javaslang/Function4.class
javaslang/Function5.class
javaslang/Function6.class
javaslang/Function7.class
javaslang/Function8.class
javaslang/Kind1.class
javaslang/Kind2.class
javaslang/Lazy.class
javaslang/MatchError.class
javaslang/Patterns.class
javaslang/Predicates.class
javaslang/Tuple.class
javaslang/Tuple0.class
javaslang/Tuple1.class
javaslang/Tuple2.class
javaslang/Tuple3.class
javaslang/Tuple4.class
javaslang/Tuple5.class
javaslang/Tuple6.class
javaslang/Tuple7.class
javaslang/Tuple8.class
javaslang/Value.class
javaslang/ValueModule.class
javaslang/λ$Memoized.class
javaslang/λ.class
META-INF/maven/io.javaslang/
META-INF/maven/io.javaslang/javaslang/
META-INF/maven/io.javaslang/javaslang/pom.xml
META-INF/maven/io.javaslang/javaslang/pom.properties
javaslang/match/
javaslang/match/annotation/
javaslang/match/annotation/Patterns.class
javaslang/match/annotation/Unapply.class
javaslang/match/generator/
javaslang/match/generator/Generator.class
javaslang/match/generator/ImportManager$FQN.class
javaslang/match/generator/ImportManager$Import.class
javaslang/match/generator/ImportManager.class
javaslang/match/model/
javaslang/match/model/ClassModel.class
javaslang/match/model/MethodModel.class
javaslang/match/model/ParameterModel.class
javaslang/match/model/TypeParameterModel.class
javaslang/match/PatternsProcessor.class
javaslang/match/UnapplyChecker.class
META-INF/services/
META-INF/services/javax.annotation.processing.Processor
META-INF/maven/io.javaslang/javaslang-match/
META-INF/maven/io.javaslang/javaslang-match/pom.xml
META-INF/maven/io.javaslang/javaslang-match/pom.properties
com/
com/amazonaws/
com/amazonaws/services/
com/amazonaws/services/lambda/
com/amazonaws/services/lambda/runtime/
com/amazonaws/services/lambda/runtime/Client.class
com/amazonaws/services/lambda/runtime/ClientContext.class
com/amazonaws/services/lambda/runtime/CognitoIdentity.class
com/amazonaws/services/lambda/runtime/Context.class
com/amazonaws/services/lambda/runtime/LambdaLogger.class
com/amazonaws/services/lambda/runtime/LambdaRuntime$1.class
com/amazonaws/services/lambda/runtime/LambdaRuntime.class
com/amazonaws/services/lambda/runtime/LambdaRuntimeInternal.class
com/amazonaws/services/lambda/runtime/RequestHandler.class
com/amazonaws/services/lambda/runtime/RequestStreamHandler.class
META-INF/maven/com.amazonaws/
META-INF/maven/com.amazonaws/aws-lambda-java-core/
META-INF/maven/com.amazonaws/aws-lambda-java-core/pom.xml
META-INF/maven/com.amazonaws/aws-lambda-java-core/pom.properties
```

**Comment by acmcelwee** [comment] 2016-12-14 03:35
Amazon says they've fixed the classloader issue. I'll test this out tomorrow and update w/ a confirmation.

https://forums.aws.amazon.com/thread.jspa?threadID=229364

**Comment by danieldietrich** [comment] 2016-12-14 11:33
Thanks for the update. I'm really looking forward to the test results!

**Comment by danieldietrich** [comment] 2016-12-16 13:13
@acmcelwee ping... :)

**Comment by acmcelwee** [comment] 2016-12-16 17:09
Not looking promising

```{
  "errorMessage": "java.lang.NoClassDefFoundError: javaslang/λ",
  "errorType": "java.lang.BootstrapMethodError",
  "stackTrace": [
    "javaslang.ShadeTest.myHandler(ShadeTest.java:18)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)"
  ],
  "cause": {
    "errorMessage": "javaslang/λ",
    "errorType": "java.lang.NoClassDefFoundError",
    "stackTrace": [
      "java.lang.ClassLoader.defineClass1(Native Method)",
      "java.lang.ClassLoader.defineClass(ClassLoader.java:763)",
      "java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)",
      "java.net.URLClassLoader.defineClass(URLClassLoader.java:467)",
      "java.net.URLClassLoader.access$100(URLClassLoader.java:73)",
      "java.net.URLClassLoader$1.run(URLClassLoader.java:368)",
      "java.net.URLClassLoader$1.run(URLClassLoader.java:362)",
      "java.security.AccessController.doPrivileged(Native Method)",
      "java.net.URLClassLoader.findClass(URLClassLoader.java:361)",
      "java.lang.ClassLoader.loadClass(ClassLoader.java:424)",
      "java.lang.ClassLoader.loadClass(ClassLoader.java:357)",
      "javaslang.ShadeTest.myHandler(ShadeTest.java:18)",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:498)"
    ],
    "cause": {
      "errorMessage": "javaslang.λ",
      "errorType": "java.lang.ClassNotFoundException",
      "stackTrace": [
        "java.net.URLClassLoader.findClass(URLClassLoader.java:381)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:424)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:357)",
        "java.lang.ClassLoader.defineClass1(Native Method)",
        "java.lang.ClassLoader.defineClass(ClassLoader.java:763)",
        "java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)",
        "java.net.URLClassLoader.defineClass(URLClassLoader.java:467)",
        "java.net.URLClassLoader.access$100(URLClassLoader.java:73)",
        "java.net.URLClassLoader$1.run(URLClassLoader.java:368)",
        "java.net.URLClassLoader$1.run(URLClassLoader.java:362)",
        "java.security.AccessController.doPrivileged(Native Method)",
        "java.net.URLClassLoader.findClass(URLClassLoader.java:361)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:424)",
        "java.lang.ClassLoader.loadClass(ClassLoader.java:357)",
        "javaslang.ShadeTest.myHandler(ShadeTest.java:18)",
        "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
        "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
        "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
        "java.lang.reflect.Method.invoke(Method.java:498)"
      ]
    }
  }
}
```

**Comment by danieldietrich** [comment] 2016-12-16 17:56
Thank you! I would love to get some technical information from Amazon/AWS _how_ they solved the problem. AWS is like a blackbox...

**Comment by danieldietrich** [comment] 2017-02-08 10:52
@acmcelwee I've looked again through this issue and saw that Gradle is used. There was another issue with Gradle that could be solved by setting the `file.encoding` system property either in JAVA_OPTS, GRADLE_OPTS or DEFAULT_JVM_OPTS. A short description can be found [here](https://github.com/johnrengelman/shadow/issues/223#issuecomment-237528182).

Do you think there is a chance that it could solve our issue here somehow? If so, could you test it with our [test-repo](https://github.com/acmcelwee/javaslang-shade-test/tree/aws-lambda)?

**Comment by acmcelwee** [comment] 2017-02-09 21:48
I've finally opened a support ticket to get amazon to dig into this some more. Their assistance on the forums kind of hit a dead end. I'll keep this thread updated if they provide any resolution.

**Comment by danieldietrich** [comment] 2017-02-10 05:56
@acmcelwee thank you for your support!

**Comment by medinarrior** [comment] 2018-09-04 19:31
Other than upgrading from javaslang to vavr my solution was the following:

$ mkdir -p target/aws
$ cd target/aws/
$ jar -xvf ../shade-test-0.0.1-SNAPSHOT.jar 
$ zip -r ../shade-test-0.0.1-SNAPSHOT.zip *

And **upload the zip file to aws**, looks like aws is using _unzip_ instead of _jar -xvf_

$ unzip -l shade-test-0.0.1-SNAPSHOT.jar | grep javaslang/λ
$ unzip -l shade-test-0.0.1-SNAPSHOT.zip | grep javaslang/λ
